### ISSUE TITLE
error: "libgcc_s.so.1 must be installed for pthread_cancel to work"

### ISSUE THREAD

**Issue by ascii78** [fuhry/initramfs-scencrypt#7] opened 2018-04-06 18:53 UTC
After bootup i have the following message:

"libgcc_s.so.1 must be installed for pthread_cancel to work"

Similar to: https://github.com/archzfs/archzfs/issues/64

Added:

    add_file "/lib/libgcc_s.so"
    add_file "/lib/libgcc_s.so.1"

to install hook fixed it.

**Comment by fuhry** [comment] 2018-08-02 16:35
Haven't seen this on my systems. But I notice that `libgcc_s.so.1` gets included by something else. Not immediately clear what includes it because I'm not using the `sd-encrypt`, `zfs` or `encrypt` hooks in my initramfs, and those are the only hooks I see in `/usr/lib/initcpio/install` that mention this library. My guess is this is added by `add_binary` as an automatically detected dependency.

Is this still an issue in the current release?

**Comment by fuhry** [comment] 2018-08-30 15:47
No reply and haven't been able to reproduce.

Closing. If anyone can reproduce, feel free to reopen.

**Closed as completed by fuhry** 2018-08-30 15:47 UTC

**Comment by niallm90** [comment] 2019-05-09 07:13
I saw this bug today on an ArchLinux install that is couple of months old. I have been using the `encrypt` hook until today when I tried to switch to this. The workaround specified by @ascii78 worked for me.

Edit: Not sure how to re-open? Do I have to create a new issue now since its been ~6 months.
